Repository TeamTuesday/siso-frontend, pull requests merged in 2022-06, with the labels that each got.

#2 Feat: [SISO-16] git message template 추가
  .gitmessage
Labels: size/S

#4 Siso 37 pr template GitHub적용
  .github/pull_request_template.md
Labels: size/S

#5 SISO-50 - SISO-50-ts-적용
  .vscode/extensions.json
  package-lock.json
  package.json
  rollup.config.js
  scripts/setupTypeScript.js
  src/App.svelte
  src/global.d.ts
  src/main.js
  src/main.ts
  tsconfig.json
Labels: size/L

#6 Router(tinro)적용 및 기본 세팅
  package-lock.json
  package.json
  src/App.svelte
  src/Router.svelte
  src/pages/List.svelte
  src/pages/Login.svelte
  src/pages/Register.svelte
Labels: size/M

#10 Feat: [SISO-64] reset.css 적용
  public/index.html
  public/minireset.css
Labels: size/S

#9 Feat: [SISO-66] alias 적용
  package-lock.json
  package.json
  rollup.config.js
  src/App.svelte
  src/Router.svelte
  src/main.ts
  tsconfig.json
Labels: size/S

#12 Feat: [SISO-65] autoprefixer 적용
  package-lock.json
  package.json
  rollup.config.js
  svelte.config.js
Labels: size/S

#11 Feat: [SISO-67] codeowners 적용
  .github/CODEOWNERS
Labels: size/XS

#14 Feat: [SISO-57] eslint 적용
  .eslintrc.js
  package-lock.json
  package.json
  rollup.config.js
  src/App.svelte
Labels: size/M

#15 Feat: [SISO-48] prettier 추가
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  public/global.css
  public/index.html
  public/minireset.css
  src/App.svelte
  src/Router.svelte
  src/pages/List.svelte
  src/pages/Login.svelte
  src/pages/Register.svelte
Labels: size/L

#16 Siso 68 pre commit 적용
  .eslintrc.js
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  rollup.config.js
  src/global.d.ts
  src/main.ts
  svelte.config.js
Labels: size/M

#7 Feat: [SISO-54] git babel 적용
  package.json
  rollup.config.js
Labels: size/S

#17 Fix: [SISO-57] module syntax error 수정
  .eslintcache
  .eslintrc.cjs
  package-lock.json
  package.json
  svelte.config.js
Labels: size/S

#19 Test: [SISO-70] 테스트 코드 적용
  .babelrc
  .eslintcache
  package-lock.json
  package.json
  src/__tests__/button.test.ts
  src/components/Button.svelte
  src/global.d.ts
  src/pages/List.svelte
  tsconfig.json
Labels: size/M
