Repository TeamTuesday/siso-frontend, pull requests merged in 2022-07, with the labels that each got.

#20 Feat: [SISO-36] 투표페이지 퍼블리싱
  .eslintrc.js
  package-lock.json
  public/images/icon/icon_back.svg
  public/images/icon/icon_comment_count.svg
  public/images/icon/icon_home.svg
  public/images/icon/icon_like_count.svg
  public/images/icon/icon_menu.svg
  public/images/icon/icon_vote_count.svg
  public/images/sample_user.svg
  src/App.svelte
  src/components/Vote.svelte
  src/pages/ButtonTest.svelte
  src/pages/List.svelte
  tsconfig.json
  types/index.d.ts
Labels: size/L

#21 Chore: [SISO-57] eslint관련 syntax error 수정
  .eslintignore
  .eslintrc.cjs
  package.json
Labels: size/XS

#22 Fix: git ignore 추가
  .gitignore
Labels: size/XS

#23 Feat: [SISO-71] 투표 목록 페이지 생성
  .gitignore
  src/Router.svelte
  src/components/Vote.svelte
  src/pages/Home.svelte
  src/pages/List.svelte
  types/index.d.ts
Labels: size/L

#25 Siso 36 투표페이지 생성
  src/Router.svelte
  src/__tests__/button.test.ts
  src/components/Button.svelte
  src/components/Common/Button.svelte
  src/components/Nav.svelte
  src/components/Vote.svelte
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteButton.svelte
  src/components/Vote/VoteContents.svelte
  src/components/Vote/VoteHeader.svelte
  src/components/Vote/VoteInfo.svelte
  src/pages/ButtonTest.svelte
  src/variables.scss
Labels: size/L

#24 Feat: [SISO-78] axios 설정 추가
  package-lock.json
  package.json
  src/service/api.ts
Labels: size/M
