Repository TeamTuesday/siso-frontend, pull requests merged in 2023-02, with the labels that each got.

#41 dotenv 추가 및 baseURL설정
  package-lock.json
  package.json
  rollup.config.js
  src/service/api.ts
Labels: size/S

#43 결과보여주기 (애니메이션 추가 전)
  src/components/Vote/VoteContents.svelte
  src/store/voteStore.ts
  src/store/voteSubjectStore.ts
  types/index.d.ts
Labels: size/L

#42 Feat: [SISO-125] 로그인, 회원가입 임시 페이지 추가
  .eslintrc.cjs
  package-lock.json
  package.json
  src/Router.svelte
  src/pages/Login.svelte
  src/pages/Register.svelte
  src/pages/auth/Login.svelte
  src/pages/auth/Register.svelte
  src/utils/Auth.ts
  tsconfig.json
  types/auth.d.ts
Labels: size/L

#45 count-up 추가
  package-lock.json
  package.json
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteContents.svelte
Labels: size/M
