Repository TeamTuesday/siso-frontend, pull requests merged in 2023-01, with the labels that each got.

#32 Feat: [SISO-103] Modal, Confirm, Profile 공통 컴포넌트 추가
  .eslintrc.cjs
  .husky/pre-commit
  public/images/icon/icn_user.svg
  src/components/common/Button.svelte
  src/components/common/button/ButtonCancel.svelte
  src/components/common/button/ButtonOk.svelte
  src/components/common/confirm/Confirm.svelte
  src/components/common/profile/Profile.svelte
  src/components/modal/Modal.svelte
  src/pages/Home.svelte
  src/utils/UI.ts
  tailwind.config.cjs
Labels: size/L

#35 투표하기 api 적용
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteContents.svelte
  src/pages/List.svelte
  src/service/api.ts
  src/store.ts
  src/store/voteStore.ts
  src/store/voteSubjectStore.ts
  types/index.d.ts
Labels: size/L

#37 Feat: [SISO-126] npm check 시 오류 수정
  package.json
  src/components/Vote/VoteContents.svelte
  src/components/common/Button.svelte
  src/components/common/confirm/Confirm.svelte
  src/components/modal/Modal.svelte
  src/pages/Home.svelte
  src/utils/UI.ts
Labels: size/M

#36 Feat: [SISO-103] 댓글 관리 모달 추가
  src/__tests__/button.test.ts
  src/__tests__/vote.test.ts
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteHeader.svelte
  src/components/Vote/VoteInfo.svelte
  src/components/common/button/Button.svelte
  src/components/common/confirm/Confirm.svelte
  src/components/common/menu/Menu.svelte
  src/components/common/modal/Modal.svelte
  src/pages/Home.svelte
  src/utils/UI.ts
  types/index.d.ts
Labels: size/L

#38 npm run check시 발생하는 router.params오류 수정
  src/components/Vote/Vote.svelte
Labels: size/XS

#40 Feat: [SISO-112] 프론트 host 옵션 추가
  package.json
Labels: size/XS
