Repository TeamTuesday/siso-frontend, pull requests merged in 2023-03, with the labels that each got.

#47 build에러 해결
  package-lock.json
  src/components/Vote/VoteContents.svelte
  src/main.ts
  types/svelte-countup.d.ts
Labels: size/M

#46 npm run check 시 오류 수정 및 mypage 테스트 코드 추가
  package-lock.json
  package.json
  src/__tests__/auth/__snapshots__/mypage.test.ts.snap
  src/__tests__/auth/mypage.test.ts
  src/components/Vote/VoteContents.svelte
  src/utils/Auth.ts
  tsconfig.json
  types/svelte-countup.d.ts
Labels: size/L

#48 step이 0이 되지 않도록
  src/components/Vote/VoteContents.svelte
Labels: size/S

#49 Feat: [SISO-99] 디자인 토큰 개발
  src/components/Vote/VoteHeader.svelte
  src/components/common/button/Button.svelte
  src/components/common/button/ButtonCancel.svelte
  src/components/common/button/ButtonOk.svelte
  src/components/common/confirm/Confirm.svelte
  src/components/common/menu/Menu.svelte
  tailwind.config.cjs
Labels: size/M

#51 Siso 146 베스트댓글 화면 추가
  public/images/icon/icn_next_gray_right.svg
  public/images/icon/icn_poll_comment.svg
  public/images/icon/icn_polled_comment.svg
  src/Router.svelte
  src/__tests__/vote.test.ts
  src/components/Vote/BestComment.svelte
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteContents.svelte
  src/components/common/button/Button.svelte
  src/store/voteStore.ts
  src/store/voteSubjectStore.ts
  types/voet.d.ts
Labels: size/L

#52 Siso 145 전환안내 애니메이션 추가
  public/images/icon/icn_next_gray_right.svg
  public/images/icon/icn_poll_comment.svg
  public/images/icon/icn_polled_comment.svg
  src/Router.svelte
  src/__tests__/vote.test.ts
  src/components/Vote/BestComment.svelte
  src/components/Vote/Vote.svelte
  src/components/Vote/VoteContents.svelte
  src/components/common/button/Button.svelte
  src/pages/Vote.svelte
  src/store/voteStore.ts
  src/store/voteSubjectStore.ts
  types/voet.d.ts
Labels: size/XL

#53 Chore: [main] build에러 해결
  src/components/Vote/VoteContents.svelte
  src/pages/Vote.svelte
Labels: size/M
